### ISSUE TITLE
Kenar çubuğu yapılabilir mi?

### ISSUE THREAD

**Issue by erkanunluturk** [dnomak/flexiblegs-scss-plus#19]
http://getbootstrap.com/examples/dashboard/ sizin kütüphaneyle bunun gibi birşey yapmak doğru olur mu?
#### ilk aklıma gelen;

*-3-12 ve *-9-12 şeklinde ki yapıda 3 olanı sabitleyip 9 a 3 ün genişliği kadar margin-left vermek, \* eklerde bunu tekrarlamak gerekiyor, bu da kodu uzatıyor.
#### bir diğeri ise;

``` html
<div class="wrapper">
  <aside class="sol"> sol </aside>
  <section class="sag">sağ </section>
</div>
```

diye ayırıp

``` css
.wrapper {
    height: 100%;
}

aside.sol {
    position: fixed;
    top: 0;
    left: 0;
    height: 100%;
    background-color: #333;
    width: 260px;
}

section.sag {
    width: calc(100% - 260px);
    margin-left:260px;
    min-height: 100%;
}
```

stillerini vererek kütaphaneyi section içinde kullanmak.

hangisi doğru olur.
